// Package onlineconf reads configuration files generated by OnlineConf.
//
// It opens indexed CDB files and maps them in the memory.
// If onlineconf-updater modifies them, they are automatically reopened.
package onlineconf

